version: '3.8'

services:
  # Servidor do Node.js (sua aplicação)
  app:
    build: .
    container_name: projeto_vendas_app
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432 # Porta interna padrão do Postgres
    depends_on:
      db:
        condition: service_healthy # Garante que o Node só inicia quando o Postgres estiver pronto para receber conexões

  # Servidor do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: projeto_vendas_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_LOCAL}:5432" # Ex: 5432:5432 ou 5433:5432 caso já tenha outro Postgres na máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapeia seu script de inicialização do Postgres para rodar automaticamente
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Volume renomeado para refletir o novo banco